[package]
name = "blog-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eight = { version = "1.0.0-alpha", features = ["macros"] }
tokio = { version = "1.28.0", features = ["full"] }
