[package]
name = "eight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["rt", "macros", "fs", "sync", "time"] }

[dev-dependencies]
tokio-test = "0.4.2"

[features]
default = []
macros = []