[package]
name = "eight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
thiserror = "1"
tokio = { version = "1", features = ["rt", "fs", "sync", "time"] }
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
tokio-test = "0.4"

[features]
default = ["embedded"]
macros = []
serde = ["dep:serde"]
embedded = []
client = []
full = ["macros", "serde", "embedded", "client"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
