name: Publish container

on:
  push:
    tags:
      - "*"
    branches:
      - "*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Tags
        run: |
          if [[ "$GITHUB_REF" == *"tags"* ]]; then
            echo TAGS="latest, ${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          else
            echo "TAGS=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Publish
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "meppu"
          password: ${{ secrets.PAT }}
          repository: meppu/eight
          tags: ${{ env.TAGS }}
