name: Run tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test for ${{ matrix.folder }}

    strategy:
      matrix:
        folder: ["eight", "eight-serve", "examples/eight-custom-storage"]

    defaults:
      run:
        working-directory: ${{ matrix.folder }}

    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.folder }}-${{ hashFiles('**/Cargo.lock') }}-deps

      - name: Build project
        run: cargo build --all-features --verbose

      - name: Run tests
        run: cargo test --all-features --verbose

      - name: Run cargo clippy
        run: cargo clippy --no-deps -- -Dwarnings

      - name: Run cargo fmt
        run: cargo fmt --check
