name: Run tests

on:
  push:
    branches: [main]
    paths:
      - eight/
      - eight-serve/
  pull_request:
    branches: [main]
    paths:
      - eight/
      - eight-serve/

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test for ${{ matrix.folder }}

    strategy:
      matrix:
        folder: [eight, eight-serve]

    defaults:
      run:
        working-directory: ${{ matrix.folder }}

    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.folder }}-${{ hashFiles('**/Cargo.lock') }}-deps

      - name: Run cargo clippy
        continue-on-error: true
        run: cargo clippy --no-deps -- -Dwarnings

      - name: Run cargo fmt
        continue-on-error: true
        run: cargo fmt --check

      - name: Build project
        run: cargo build --all-features --verbose

      - name: Run tests
        run: cargo test --all-features --verbose
